import { EstadoLead } from "generated/prisma/client";

export const LEAD_TRANSITIONS: Record<EstadoLead, EstadoLead[]> = {
	NUEVO: ["CONTACTADO", "INTERESADO", "CITA_AGENDADA", "PERDIDO"],
	CONTACTADO: ["CALIFICADO", "INTERESADO", "CITA_AGENDADA", "PERDIDO"],
	CALIFICADO: ["INTERESADO", "CITA_AGENDADA", "NEGOCIACION", "PERDIDO"],
	INTERESADO: ["CITA_AGENDADA", "NEGOCIACION", "GANADO", "PERDIDO"],
	CITA_AGENDADA: ["NEGOCIACION", "GANADO", "PERDIDO"],
	NEGOCIACION: ["GANADO", "PERDIDO"],
	GANADO: [],
	PERDIDO: [],
};

export const ALLOWED_MANUAL_TRANSITIONS: EstadoLead[] = ["CALIFICADO", "NEGOCIACION", "PERDIDO"];